### ISSUE TITLE
How to run web example

### ISSUE THREAD

**Issue by loothood** [RustVis/jiao#1]
Hi, thank you for the project.

Could you please add some documentation on how to run example projects? For example, I want to understand how to run the web example.

**Comment by XuShaohua** [comment]
There is a dependency issue and has been fixed in latest pr.
cd examples/web and `trunk serve`, then visit http://localhost:8080 in browser.

NOTE: This crate (as version 0.1) is developed in early stage(prove of concept), and might be changed extensively.
Thanks for your attention
